const { ChatOpenAI } = require("@langchain/openai");
const { PromptTemplate } = require("@langchain/core/prompts");
const { StringOutputParser } = require("@langchain/core/output_parsers");

/**
 * Sends the user query and retrieved context to the OpenAI GPT model.
 * Forces the model to answer based ONLY on the provided documents.
 * 
 * @param {string} query - The user's question
 * @param {string[]} contextChunks - Array of relevant text chunks from the vector store
 * @returns {Promise<string>} The contextual answer generated by OpenAI
 */
const generateAnswer = async (query, contextChunks) => {
    try {
        if (!process.env.OPENAI_API_KEY) {
            throw new Error("OPENAI_API_KEY is missing from environment variables");
        }

        // Initialize the Chat Model
        const model = new ChatOpenAI({
            openAIApiKey: process.env.OPENAI_API_KEY,
            modelName: "gpt-3.5-turbo", // You can switch to "gpt-4o" if preferred
            temperature: 0, // 0 prevents hallucination and keeps it grounded
        });

        // Combine array of object chunks into one large string block for context, including the source page numbers
        const contextText = contextChunks.length > 0
            ? contextChunks.map(c => `[Source: Page ${c.page}]\n${c.text}`).join("\n\n---\n\n")
            : "No relevant documents found.";

        // Define the strict prompt instructions
        const promptTemplate = PromptTemplate.fromTemplate(`
You are a helpful and reliable AI assistant. 
Use the following pieces of retrieved context to answer the user's question.
If the answer is not contained within the provided context, clearly state "I don't know based on the provided documents." Do not try to make up an answer or use outside knowledge.

Crucially: When you answer a question using the context, you MUST append the exact source page number at the very end of your answer, formatted exactly as: "\\n\\nSource: Page X".
If you use information from multiple pages, append them all like: "\\n\\nSource: Page X, Page Y".

Context:
{context}

Question: {question}

Answer:`);

        // Create the execution chain
        const chain = promptTemplate.pipe(model).pipe(new StringOutputParser());

        // Execute the chain
        const result = await chain.invoke({
            context: contextText,
            question: query
        });

        return result;
    } catch (error) {
        console.error("Error generating answer from OpenAI:", error);
        throw new Error(`Failed to generate answer: ${error.message}`);
    }
};

module.exports = {
    generateAnswer
};
